### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Allmight00001** [DEVILENMO/DeadEyeAutoAimingSystem#1]
C:\Users\Administrator\Documents\DeadEyeAutoAimingSystem-master>C:\Users\Administrator\Documents\DeadEyeAutoAimingSystem-master\main.py
Initing detect module...
Initing auto aiming module...
Initing DeadEye core system...
System is set to paused state while initing.
Screen resolution: 1920 x 1080
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\DeadEyeAutoAimingSystem-master\main.py", line 268, in <module>
    dead_eye = DeadEyeCore(detect_module, auto_aiming_module, view_range)
  File "C:\Users\Administrator\Documents\DeadEyeAutoAimingSystem-master\DeadEyeCore.py", line 51, in __init__
    self.rel_resolution_x, self.rel_resolution_y = dxcam.output_res()[0]
AttributeError: module 'dxcam' has no attribute 'output_res'. Did you mean: 'output_info'?

**Comment by DEVILENMO** [comment]
I forgot to include the necessary code changes. The attribute `output_res` is added by myself. Here are the steps to add it:

1. Go to the declaration of `dxcam`, locate the `__init__` file, and add the following method after the `def output_info(self) -> str: ......` method near line 88:

   ```python
   def output_res(self):
       res = []
       for didx, outputs in enumerate(self.outputs):
           for idx, output in enumerate(outputs):
               res.append(output.resolution)
       return res
   ```

2. Add another method after the `def output_info(): ......` method near line 132:

   ```python
   def output_res():
       return __factory.output_res()
   ```

After making these changes, it should work as expected.

Additionally, you can ignore lines 50 and 51 of `DeadEyeCore`. These two lines were written for debugging the display resolution conflict and have no real usage in the final code.

**Comment by DEVILENMO** [comment]
You can directly resolve the issue by commenting out lines 50 and 51 in `DeadEyeCore`:

```python
self.rel_resolution_x, self.rel_resolution_y = dxcam.output_res()[0]
print('Scaled screen resolution:', self.rel_resolution_x, 'x', self.rel_resolution_y)
```
Change them to:
```python
# self.rel_resolution_x, self.rel_resolution_y = dxcam.output_res()[0]
# print('Scaled screen resolution:', self.rel_resolution_x, 'x', self.rel_resolution_y)
```
I will comment out these lines in the next code update to address this issue.

**Comment by DEVILENMO** [comment]
I’m not sure if you can resolve the problem by doing this, if so, I will close this issue.

**Comment by Allmight00001** [comment]
Even with the change I still get the same errors

**Comment by Allmight00001** [comment]
Device info: Device[0]:<Device Name:NVIDIA GeForce RTX 3080 Ti Dedicated VRAM:12086Mb VendorId:4318> 
Output info: Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True 
system32 system resolution： (1920, 1080)
Traceback (most recent call last):
  File "c:\DeadEyeAutoAimingSystem-master\main.py", line 268, in <module>
    dead_eye = DeadEyeCore(detect_module, auto_aiming_module, view_range)
  File "c:\DeadEyeAutoAimingSystem-master\DeadEyeCore.py", line 52, in __init__
    self.screen_shot_camera = ScreenShotHelper(view_range[0], view_range[1], ScreenShotHelper.CameraType.DXCAM)
  File "c:\DeadEyeAutoAimingSystem-master\ScreenShotHelper.py", line 28, in __init__
    print('dxcam system resolution:', dxcam.output_res()[0])
AttributeError: module 'dxcam' has no attribute 'output_res'. Did you mean: 'output_info'?

**Comment by DEVILENMO** [comment]
Well, this is the modefied `__init__` file of dxcam, replace the original file, then it should be fixed.
```python
import weakref
import time
from dxcam.dxcam import DXCamera, Output, Device
from dxcam.util.io import (
    enum_dxgi_adapters,
    get_output_metadata,
)


class Singleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        else:
            print(f"Only 1 instance of {cls.__name__} is allowed.")

        return cls._instances[cls]


class DXFactory(metaclass=Singleton):

    _camera_instances = weakref.WeakValueDictionary()

    def __init__(self) -> None:
        p_adapters = enum_dxgi_adapters()
        self.devices, self.outputs = [], []
        for p_adapter in p_adapters:
            device = Device(p_adapter)
            p_outputs = device.enum_outputs()
            if len(p_outputs) != 0:
                self.devices.append(device)
                self.outputs.append([Output(p_output) for p_output in p_outputs])
        self.output_metadata = get_output_metadata()

    def create(
        self,
        device_idx: int = 0,
        output_idx: int = None,
        region: tuple = None,
        output_color: str = "RGB",
        max_buffer_len: int = 64,
    ):
        device = self.devices[device_idx]
        if output_idx is None:
            # Select Primary Output
            output_idx = [
                idx
                for idx, metadata in enumerate(
                    self.output_metadata.get(output.devicename)
                    for output in self.outputs[device_idx]
                )
                if metadata[1]
            ][0]
        instance_key = (device_idx, output_idx)
        if instance_key in self._camera_instances:
            print(
                "".join(
                    (
                        f"You already created a DXCamera Instance for Device {device_idx}--Output {output_idx}!\n",
                        "Returning the existed instance...\n",
                        "To change capture parameters you can manually delete the old object using `del obj`.",
                    )
                )
            )
            return self._camera_instances[instance_key]

        output = self.outputs[device_idx][output_idx]
        output.update_desc()
        camera = DXCamera(
            output=output,
            device=device,
            region=region,
            output_color=output_color,
            max_buffer_len=max_buffer_len,
        )
        self._camera_instances[instance_key] = camera
        time.sleep(0.1)  # Fix for https://github.com/ra1nty/DXcam/issues/31
        return camera

    def device_info(self) -> str:
        ret = ""
        for idx, device in enumerate(self.devices):
            ret += f"Device[{idx}]:{device}\n"
        return ret

    def output_info(self) -> str:
        ret = ""
        for didx, outputs in enumerate(self.outputs):
            for idx, output in enumerate(outputs):
                ret += f"Device[{didx}] Output[{idx}]: "
                ret += f"Res:{output.resolution} Rot:{output.rotation_angle}"
                ret += f" Primary:{self.output_metadata.get(output.devicename)[1]}\n"
        return ret

    def output_res(self):
        res = []
        for didx, outputs in enumerate(self.outputs):
            for idx, output in enumerate(outputs):
                res.append(output.resolution)
        return res

    def clean_up(self):
        for _, camera in self._camera_instances.items():
            camera.release()


__factory = DXFactory()


def create(
    device_idx: int = 0,
    output_idx: int = None,
    region: tuple = None,
    output_color: str = "RGB",
    max_buffer_len: int = 64,
):
    return __factory.create(
        device_idx=device_idx,
        output_idx=output_idx,
        region=region,
        output_color=output_color,
        max_buffer_len=max_buffer_len,
    )


def device_info():
    return __factory.device_info()


def output_info():
    return __factory.output_info()

def output_res():
    return __factory.output_res()
```
You can find the file by right clicking at the `dxcam`, and choose the option as the picture shows.
![image](https://github.com/DEVILENMO/DeadEyeAutoAimingSystem/assets/51067504/969f7637-25ff-40f8-b3bf-34f7f1d8d774)
I can't remember clearly if it is the only file I changed in the dxcam, if still has error, you can keep in torch with me.

**Comment by DEVILENMO** [comment]
By the way, the old version of `dxcam` is supposed to have this key function directly, in my old version code I directly use this attribute/function without any changing. But the newly installed `dxcam` remove it, so I re-added it. This is the reason behind the problem, and I think it is easy to fix, you can also written the function as you want, more then one resolution exists here.
