### ISSUE TITLE
你好你好

### ISSUE THREAD

**Issue by Lws0530** [DEVILENMO/DeadEyeAutoAimingSystem#3]
https://github.com/DEVILENMO/DeadEye-Auto-Aiming-System/issues/2#issuecomment-2492910171

麻烦您帮我看下代码是否正确  能不能帮我修改一下呢

**Comment by DEVILENMO** [comment]
在你前一个issue中给你了大概的修改参考，具体有问题自己再调整一下吧，我手头没有电脑来测试
